Icinga/icingaweb2-module-graphite

configuration.php
=> Move "Graphite" Navigation

application/controllers/ConfigController.php, application/forms/ConfigForm.php, application/views/scripts/config/index.phtml, configuration.php
=> Make the Graphite Web URL configurable over the WebUI

application/controllers/ShowController.php, application/forms/ConfigForm.php, library/Graphite/GraphiteChart.php, library/Graphite/GraphiteWeb.php, library/Graphite/GraphiteWebClient.php, library/Graphite/GraphiteWebClientInterface.php, library/Graphite/Pattern/Singleton.php, library/Graphite/Web/Form/Validator/HttpUserValidator.php
=> Support Graphite Web with HTTP basic authn

application/controllers/GraphController.php, application/controllers/ShowController.php, library/Graphite/Web/Widget/Graphs.php, library/Graphite/Web/Widget/Graphs/Host.php, library/Graphite/Web/Widget/Graphs/Service.php, library/Graphite/Web/Widget/GraphsTrait.php
=> Implement simple-to-use image URLs /graph/*

library/Graphite/Graphing/GraphingTrait.php, templates/disk.ini, templates/hostalive.ini, templates/http.ini, templates/icinga.ini, templates/load.ini, templates/ping4.ini, templates/procs.ini, templates/ssh.ini, templates/swap.ini
=> Port all templates and load them automatically

library/Graphite/ProvidedHook/Monitoring/DetailviewExtension.php, library/Graphite/Web/Widget/Graphs.php, public/css/module.less, public/js/module.js
=> Monitored objects' detailview extension: enlarge the graphs dynamically

application/controllers/ListController.php, application/views/scripts/list/hosts.phtml, application/views/scripts/list/services.phtml, library/Graphite/Graphing/Template.php, library/Graphite/Graphing/Templates.php, library/Graphite/Web/Widget/Graphs.php, library/Graphite/Web/Widget/Graphs/Host.php, library/Graphite/Web/Widget/Graphs/Service.php
=> Query only the templates designed for the monitored object's check command

application/controllers/GraphController.php, application/controllers/ListController.php, application/views/scripts/list/hosts.phtml, application/views/scripts/list/services.phtml, library/Graphite/Graphing/Template.php, library/Graphite/Graphing/Templates.php, library/Graphite/Util/MacroTemplate.php, library/Graphite/Web/Widget/Graphs.php, library/Graphite/Web/Widget/Graphs/Host.php, library/Graphite/Web/Widget/Graphs/Service.php
=> Make working with check_by_ssh

application/controllers/GraphDummyController.php, library/Graphite/ProvidedHook/Monitoring/DetailviewExtension.php, library/Graphite/Web/Widget/Graphs.php, library/Graphite/Web/Widget/Graphs/Host.php, library/Graphite/Web/Widget/Graphs/Service.php, public/js/module.js
=> Reduce eye cancer causes during graphs loading

application/forms/TimeRangePicker/CommonForm.php
=> Pre-select range "1 hour" by default

application/controllers/ListController.php, application/forms/TimeRangePicker/CustomForm.php, application/forms/TimeRangePicker/TimeRangePickerTrait.php, library/Graphite/Web/Controller/TimeRangePickerTrait.php, public/css/module.less
=> Use flyover in time range picker

application/controllers/ListController.php, application/forms/Config/AdvancedForm.php, doc/03-Configuration.md, library/Graphite/Web/Widget/Graphs.php
=> Parameterize the service variable vars.check_command

application/forms/Config/AdvancedForm.php, application/forms/TimeRangePicker/CommonForm.php, application/forms/TimeRangePicker/TimeRangePickerTrait.php, doc/03-Configuration.md, library/Graphite/Web/Widget/Graphs.php
=> Add global option to set default time range

application/forms/Config/AdvancedForm.php, application/views/scripts/list/hosts.phtml, doc/03-Configuration.md, library/Graphite/Web/Widget/Graphs.php
=> Add setting: Disable "no graphs found"

application/forms/Config/BackendForm.php, library/Graphite/Graphing/GraphingTrait.php, library/Graphite/Graphing/GraphiteWebClient.php
=> Add switch for insecure TLS

library/Graphite/Graphing/GraphingTrait.php, library/Graphite/Graphing/GraphiteWebClient.php, library/Graphite/Web/FakeSchemeRequest.php
=> Preserve the configured Graphite Web URL as is

doc/04-Templates.md, library/Graphite/Graphing/Templates.php
=> Allow not to specify any metrics to disable the graph

module.info
=> Add description

application/forms/Config/AdvancedForm.php
=> Fix form element validation

doc/04-Templates.md, library/Graphite/Graphing/Templates.php
=> Add optional default URL params

templates/interfacetable.ini
=> Add template for interfacetable

library/Graphite/Web/Widget/Graphs.php
=> Group graphs by service elements

library/Graphite/Graphing/Template.php
=> Reduce CPU time while combining metrics for multi-curve graphs

templates/default.ini, templates/disk.ini, templates/file_age.ini, templates/fping.ini, templates/hostalive.ini, templates/icinga.ini, templates/icmp.ini, templates/load.ini, templates/mailq.ini, templates/memory.ini, templates/network.ini, templates/ntp_time.ini, templates/ping.ini, templates/procs.ini, templates/response-size.ini, templates/response-time.ini, templates/swap.ini, templates/update.ini, templates/uptime.ini, templates/users.ini
=> Templates: unify lineWidth

application/controllers/GraphController.php, application/forms/TimeRangePicker/CustomForm.php, library/Graphite/Graphing/Chart.php
=> Respect a user's timezone preferences

library/Graphite/Graphing/Chart.php
=> Try to workaround division by zero

application/controllers/GraphController.php, library/Graphite/Graphing/Template.php, library/Graphite/Graphing/Templates.php, library/Graphite/Web/Widget/Graphs.php
=> Display charts based on the default template(s) assembled from metrics not covered by concrete templates' filters

configuration.php, doc/01-About.md, doc/05-Troubleshooting.md, library/Graphite/Graphing/GraphiteWebClient.php, library/Graphite/Graphing/MetricsQuery.php, library/Graphite/Graphing/Template.php, library/Graphite/ProvidedHook/Monitoring/DetailviewExtension.php, library/Graphite/Util/InternalProcessTracker.php, library/Graphite/Web/Widget/Graphs.php
=> Implement optional graphs assembling debugging

library/Graphite/Graphing/MetricsQuery.php
=> Handle monitored object names containing "$"

application/controllers/ListController.php, configuration.php, library/Graphite/Web/Widget/Graphs.php, library/Graphite/Web/Widget/Graphs/Host.php, library/Graphite/Web/Widget/Graphs/Service.php, public/css/module.less
=> Limit graphs loaded by default per monitored object

library/vendor/iplx/Http/Client.php
=> Properly initialize $handles

application/controllers/GraphController.php, application/controllers/ListController.php, application/views/scripts/list/hosts.phtml, application/views/scripts/list/services.phtml, library/Graphite/Graphing/Chart.php, library/Graphite/Graphing/MetricsQuery.php, library/Graphite/Graphing/Template.php, library/Graphite/Web/Widget/Graphs.php, library/Graphite/Web/Widget/Graphs/Host.php, library/Graphite/Web/Widget/Graphs/Service.php
=> Metric paths: support all monitored object core attributes provided by the monitoring module

library/Graphite/Web/Widget/GraphImage.php
=> Fix wrong method of request to Graphite Web

library/Graphite/Graphing/MetricsQuery.php
=> Don't escape ' in metrics

doc/02-Installation.md, doc/03-Configuration.md, doc/04-Templates.md
Thanks for the great integration
=> Minor documentation tweaks

public/js/module.js
=> Fix usage of deprecated jquery method load

application/views/scripts/list/services.phtml
=> Fix invalid HTML in service list

doc/04-Templates.md, library/Graphite/Graphing/Templates.php, library/Graphite/Web/Widget/GraphImage.php
=> Make all macros used in a template's metrics filters available in its functions, too

application/controllers/ListController.php
Hi,
services that don't have perfdata can be removed from the list.
This is my first pull-request ever, so I hope I did it correctly...
=> Filter Services with no perfdata

library/Graphite/Web/Controller/TimeRangePickerTrait.php
=> Disable autorefreshes while timerange picker is open

doc/04-Templates.md
=> 04-Templates.md: Add note for required sections of template file

doc/05-Troubleshooting.md
=> Add doc for special chars

templates/ethMon.ini
A template for the ethMon plugin available @exchange.icinga.com.
The plugin has been published a few hours ago :-)
In case that someone decides to use it, it would be nice for the graphs to have style right away.
A sample using the template is attached below.
=> ethMon template

application/controllers/MonitoringGraphController.php, library/Graphite/Web/Controller/MonitoringAwareController.php, run.php
=> Split `icingadb` and `monitoring` graph controllers

.github/workflows/php.yml, README.md, doc/02-Installation.md.d/From-Source.md
Do not drop PHP 7.2 support yet.
=> Undo dropping of PHP 7.2 support

application/controllers/HostsController.php, application/controllers/ServicesController.php, library/Graphite/Web/Controller/IcingadbGraphiteController.php
=> Preserve `format` reqeust param
